const users = require("./routes/users");
const auth = require("./routes/auth");
const cards = require("./routes/cards");
const upload = require("./routes/upload");
const express = require("express");
const path = require("path");
const app = express();
const http = require("http").Server(app);
const cors = require("cors");
const mongodb = require("./db/mongoConnect");
app.use("/public", express.static(path.join(__dirname, "public")));
app.use(cors());
app.use(express.json());
app.use("/api/users", users);
app.use("/api/auth", auth);
app.use("/api/cards", cards);
app.use("/api/upload", upload);

const port = process.env.PORT || 3900;
http.listen(port, () => console.log(`Listening on port ${port}...`));
